import { Achievement } from './types';

export const ACHIEVEMENTS: Achievement[] = [
  // --- ACIERTOS TOTALES (28) ---
  { id: 'hits_1', name: 'Primer Acierto', description: 'Gana tu primera combinada.', points: 1, icon: 'Target' },
  { id: 'hits_2', name: 'Doble Impacto', description: 'Acumula 2 combinadas ganadas.', points: 2, icon: 'Target' },
  { id: 'hits_3', name: 'Triplete Ganador', description: 'Acumula 3 combinadas ganadas.', points: 3, icon: 'Target' },
  { id: 'hits_4', name: 'Cuarteto de Éxito', description: 'Acumula 4 combinadas ganadas.', points: 4, icon: 'Target' },
  { id: 'hits_5', name: 'Mano Llena', description: 'Acumula 5 combinadas ganadas.', points: 5, icon: 'Target' },
  { id: 'hits_7', name: 'Siete de la Suerte', description: 'Acumula 7 combinadas ganadas.', points: 10, icon: 'Target' },
  { id: 'hits_10', name: 'Diez de Diez', description: 'Acumula 10 combinadas ganadas.', points: 20, icon: 'Target' },
  { id: 'hits_15', name: 'Quinceañero', description: 'Acumula 15 combinadas ganadas.', points: 30, icon: 'Target' },
  { id: 'hits_20', name: 'Vigésimo Triunfo', description: 'Acumula 20 combinadas ganadas.', points: 40, icon: 'Target' },
  { id: 'hits_25', name: 'Bodas de Plata', description: 'Acumula 25 combinadas ganadas.', points: 50, icon: 'Target' },
  { id: 'hits_30', name: 'Treintañero', description: 'Acumula 30 combinadas ganadas.', points: 60, icon: 'Target' },
  { id: 'hits_40', name: 'Cuarentón Exitoso', description: 'Acumula 40 combinadas ganadas.', points: 80, icon: 'Target' },
  { id: 'hits_50', name: 'Medio Siglo de Éxitos', description: 'Acumula 50 combinadas ganadas.', points: 100, icon: 'Target' },
  { id: 'hits_60', name: 'Sesenta Victorias', description: 'Acumula 60 combinadas ganadas.', points: 120, icon: 'Target' },
  { id: 'hits_70', name: 'Setenta Maravillas', description: 'Acumula 70 combinadas ganadas.', points: 140, icon: 'Target' },
  { id: 'hits_80', name: 'Ochenta Logros', description: 'Acumula 80 combinadas ganadas.', points: 160, icon: 'Target' },
  { id: 'hits_90', name: 'Noventa y Contando', description: 'Acumula 90 combinadas ganadas.', points: 180, icon: 'Target' },
  { id: 'hits_100', name: 'Centenario', description: 'Acumula 100 combinadas ganadas.', points: 250, icon: 'Trophy' },
  { id: 'hits_125', name: 'Más que un Siglo', description: 'Acumula 125 combinadas ganadas.', points: 300, icon: 'Trophy' },
  { id: 'hits_150', name: 'Ciento Cincuenta', description: 'Acumula 150 combinadas ganadas.', points: 350, icon: 'Trophy' },
  { id: 'hits_175', name: 'Hacia los Doscientos', description: 'Acumula 175 combinadas ganadas.', points: 400, icon: 'Trophy' },
  { id: 'hits_200', name: 'Bicentenario', description: 'Acumula 200 combinadas ganadas.', points: 500, icon: 'Trophy' },
  { id: 'hits_250', name: 'Cuarto de Millar', description: 'Acumula 250 combinadas ganadas.', points: 600, icon: 'Trophy' },
  { id: 'hits_300', name: 'Trescientos Espartanos', description: 'Acumula 300 combinadas ganadas.', points: 750, icon: 'Trophy' },
  { id: 'hits_400', name: 'Cuatrocientos Golpes', description: 'Acumula 400 combinadas ganadas.', points: 1000, icon: 'Trophy' },
  { id: 'hits_500', name: 'Medio Millar de Gloria', description: 'Acumula 500 combinadas ganadas.', points: 1500, icon: 'Trophy' },
  { id: 'hits_750', name: 'Tres Cuartos de Éxito', description: 'Acumula 750 combinadas ganadas.', points: 2500, icon: 'Trophy' },
  { id: 'hits_1000', name: 'Milenario de Oro', description: 'Acumula 1000 combinadas ganadas.', points: 5000, icon: 'Trophy' },

  // --- NIVELES (19) ---
  { id: 'level_2', name: 'Ascenso Rápido', description: 'Alcanza el nivel 2.', points: 5, icon: 'TrendingUp' },
  { id: 'level_3', name: 'Subiendo Escalones', description: 'Alcanza el nivel 3.', points: 10, icon: 'TrendingUp' },
  { id: 'level_4', name: 'En Crecimiento', description: 'Alcanza el nivel 4.', points: 15, icon: 'TrendingUp' },
  { id: 'level_5', name: 'Quinto Elemento', description: 'Alcanza el nivel 5.', points: 20, icon: 'TrendingUp' },
  { id: 'level_7', name: 'Nivel de la Suerte', description: 'Alcanza el nivel 7.', points: 30, icon: 'TrendingUp' },
  { id: 'level_10', name: 'Doble Dígito', description: 'Alcanza el nivel 10.', points: 50, icon: 'TrendingUp' },
  { id: 'level_15', name: 'Adolescente Digital', description: 'Alcanza el nivel 15.', points: 75, icon: 'TrendingUp' },
  { id: 'level_20', name: 'Mayoría de Edad', description: 'Alcanza el nivel 20.', points: 100, icon: 'TrendingUp' },
  { id: 'level_25', name: 'Cuarto de Camino', description: 'Alcanza el nivel 25.', points: 150, icon: 'TrendingUp' },
  { id: 'level_30', name: 'Treinta y Pujante', description: 'Alcanza el nivel 30.', points: 200, icon: 'TrendingUp' },
  { id: 'level_35', name: 'Madurez en Apuestas', description: 'Alcanza el nivel 35.', points: 250, icon: 'TrendingUp' },
  { id: 'level_40', name: 'Veterano', description: 'Alcanza el nivel 40.', points: 300, icon: 'TrendingUp' },
  { id: 'level_45', name: 'Casi a la Mitad', description: 'Alcanza el nivel 45.', points: 400, icon: 'TrendingUp' },
  { id: 'level_50', name: 'Cima Intermedia', description: 'Alcanza el nivel 50.', points: 500, icon: 'TrendingUp' },
  { id: 'level_60', name: 'Sesenta y Sabio', description: 'Alcanza el nivel 60.', points: 750, icon: 'TrendingUp' },
  { id: 'level_70', name: 'Setenta y Experto', description: 'Alcanza el nivel 70.', points: 1000, icon: 'TrendingUp' },
  { id: 'level_80', name: 'Ochenta y Maestro', description: 'Alcanza el nivel 80.', points: 1500, icon: 'TrendingUp' },
  { id: 'level_90', name: 'Noventa y Élite', description: 'Alcanza el nivel 90.', points: 2000, icon: 'TrendingUp' },
  { id: 'level_100', name: 'Leyenda Viviente', description: 'Alcanza el nivel 100.', points: 5000, icon: 'TrendingUp' },

  // --- RACHAS (12) ---
  { id: 'streak_2', name: 'Dúo Dinámico', description: 'Gana 2 combinadas consecutivas.', points: 5, icon: 'Zap' },
  { id: 'streak_3', name: 'Racha de 3', description: 'Gana 3 combinadas consecutivas.', points: 15, icon: 'Zap' },
  { id: 'streak_4', name: 'Póker de Victorias', description: 'Gana 4 combinadas consecutivas.', points: 30, icon: 'Zap' },
  { id: 'streak_5', name: 'Repóker', description: 'Gana 5 combinadas consecutivas.', points: 50, icon: 'Zap' },
  { id: 'streak_6', name: 'Sexteto Imparable', description: 'Gana 6 combinadas consecutivas.', points: 75, icon: 'Zap' },
  { id: 'streak_7', name: 'Semana de Fuego', description: 'Gana 7 combinadas consecutivas.', points: 100, icon: 'Zap' },
  { id: 'streak_8', name: 'Octava Maravilla', description: 'Gana 8 combinadas consecutivas.', points: 150, icon: 'Zap' },
  { id: 'streak_9', name: 'Nueve Vidas', description: 'Gana 9 combinadas consecutivas.', points: 200, icon: 'Zap' },
  { id: 'streak_10', name: 'Perfección Diez', description: 'Gana 10 combinadas consecutivas.', points: 300, icon: 'Zap' },
  { id: 'streak_12', name: 'Docena de Oro', description: 'Gana 12 combinadas consecutivas.', points: 500, icon: 'Zap' },
  { id: 'streak_15', name: 'Quince de Gala', description: 'Gana 15 combinadas consecutivas.', points: 1000, icon: 'Zap' },
  { id: 'streak_20', name: 'Inmortalidad en Racha', description: 'Gana 20 combinadas consecutivas.', points: 2500, icon: 'Zap' },

  // --- COPIADOS (16) ---
  { id: 'copied_1', name: 'Influencer Novato', description: 'Tu apuesta ha sido copiada una vez.', points: 5, icon: 'Users' },
  { id: 'copied_5', name: 'Llamando la Atención', description: 'Tus apuestas han sido copiadas 5 veces.', points: 15, icon: 'Users' },
  { id: 'copied_10', name: 'Líder de Opinión', description: 'Tus apuestas han sido copiadas 10 veces.', points: 30, icon: 'Users' },
  { id: 'copied_20', name: 'Referente Local', description: 'Tus apuestas han sido copiadas 20 veces.', points: 50, icon: 'Users' },
  { id: 'copied_30', name: 'Gurú de la Comunidad', description: 'Tus apuestas han sido copiadas 30 veces.', points: 75, icon: 'Users' },
  { id: 'copied_40', name: 'Maestro de Seguidores', description: 'Tus apuestas han sido copiadas 40 veces.', points: 100, icon: 'Users' },
  { id: 'copied_50', name: 'Oráculo Popular', description: 'Tus apuestas han sido copiadas 50 veces.', points: 150, icon: 'Users' },
  { id: 'copied_75', name: 'Leyenda en Ciernes', description: 'Tus apuestas han sido copiadas 75 veces.', points: 250, icon: 'Users' },
  { id: 'copied_100', name: 'Estrella de FictiBET', description: 'Tus apuestas han sido copiadas 100 veces.', points: 500, icon: 'Users' },
  { id: 'copied_150', name: 'Superestrella', description: 'Tus apuestas han sido copiadas 150 veces.', points: 750, icon: 'Users' },
  { id: 'copied_200', name: 'Ídolo de Masas', description: 'Tus apuestas han sido copiadas 200 veces.', points: 1000, icon: 'Users' },
  { id: 'copied_300', name: 'Mito Viviente', description: 'Tus apuestas han sido copiadas 300 veces.', points: 1500, icon: 'Users' },
  { id: 'copied_400', name: 'Deidad de Pronósticos', description: 'Tus apuestas han sido copiadas 400 veces.', points: 2000, icon: 'Users' },
  { id: 'copied_500', name: 'Inmortal Social', description: 'Tus apuestas han sido copiadas 500 veces.', points: 3000, icon: 'Users' },
  { id: 'copied_750', name: 'Omnipresente', description: 'Tus apuestas han sido copiadas 750 veces.', points: 5000, icon: 'Users' },
  { id: 'copied_1000', name: 'Dios de las Apuestas', description: 'Tus apuestas han sido copiadas 1000 veces.', points: 10000, icon: 'Users' },

  // --- DÍAS CONSECUTIVOS (14) ---
  { id: 'days_2', name: 'Día Dos', description: 'Apuesta 2 días seguidos.', points: 2, icon: 'Calendar' },
  { id: 'days_3', name: 'Tres son Multitud', description: 'Apuesta 3 días seguidos.', points: 5, icon: 'Calendar' },
  { id: 'days_4', name: 'Cuatro Fantásticos', description: 'Apuesta 4 días seguidos.', points: 10, icon: 'Calendar' },
  { id: 'days_5', name: 'Semana Laboral', description: 'Apuesta 5 días seguidos.', points: 15, icon: 'Calendar' },
  { id: 'days_6', name: 'Casi una Semana', description: 'Apuesta 6 días seguidos.', points: 20, icon: 'Calendar' },
  { id: 'days_7', name: 'Semana Perfecta', description: 'Apuesta 7 días seguidos.', points: 50, icon: 'Calendar' },
  { id: 'days_10', name: 'Diez Días de Gloria', description: 'Apuesta 10 días seguidos.', points: 75, icon: 'Calendar' },
  { id: 'days_14', name: 'Quincena de Apuestas', description: 'Apuesta 14 días seguidos.', points: 150, icon: 'Calendar' },
  { id: 'days_21', name: 'Tres Semanas', description: 'Apuesta 21 días seguidos.', points: 250, icon: 'Calendar' },
  { id: 'days_30', name: 'Mes de Constancia', description: 'Apuesta 30 días seguidos.', points: 500, icon: 'Calendar' },
  { id: 'days_60', name: 'Bimestre Fiel', description: 'Apuesta 60 días seguidos.', points: 1000, icon: 'Calendar' },
  { id: 'days_90', name: 'Trimestre de Oro', description: 'Apuesta 90 días seguidos.', points: 1500, icon: 'Calendar' },
  { id: 'days_180', name: 'Semestre de Leyenda', description: 'Apuesta 180 días seguidos.', points: 3000, icon: 'Calendar' },
  { id: 'days_365', name: 'Un Año de FictiBET', description: 'Apuesta 365 días seguidos.', points: 10000, icon: 'Calendar' },

  // --- CUOTAS ALTAS (7) ---
  { id: 'odds_2', name: 'Doblador', description: 'Gana una apuesta con cuota mayor a 2.0.', points: 5, icon: 'Star' },
  { id: 'odds_3', name: 'Triplicador', description: 'Gana una apuesta con cuota mayor a 3.0.', points: 15, icon: 'Star' },
  { id: 'odds_5', name: 'Quintintuplicador', description: 'Gana una apuesta con cuota mayor a 5.0.', points: 50, icon: 'Star' },
  { id: 'odds_10', name: 'Diez Veces Más', description: 'Gana una apuesta con cuota mayor a 10.0.', points: 150, icon: 'Star' },
  { id: 'odds_20', name: 'Veinte Veces Más', description: 'Gana una apuesta con cuota mayor a 20.0.', points: 500, icon: 'Star' },
  { id: 'odds_50', name: 'Cincuenta Veces Más', description: 'Gana una apuesta con cuota mayor a 50.0.', points: 1500, icon: 'Star' },
  { id: 'odds_100', name: 'El Gran Golpe', description: 'Gana una apuesta con cuota mayor a 100.0.', points: 5000, icon: 'Star' },

  // --- COMBINADAS GRANDES (4) ---
  { id: 'parlay_3', name: 'Tripleta Ganadora', description: 'Gana una combinada de 3 partidos.', points: 20, icon: 'Layers' },
  { id: 'parlay_4', name: 'Cuádruple de Éxito', description: 'Gana una combinada de 4 partidos.', points: 50, icon: 'Layers' },
  { id: 'parlay_5', name: 'Quíntuple de Gloria', description: 'Gana una combinada de 5 partidos.', points: 150, icon: 'Layers' },
  { id: 'parlay_6', name: 'Sextuple Legendaria', description: 'Gana una combinada de 6 partidos.', points: 500, icon: 'Layers' }
];

export function calculateLevel(hits: number): number {
  return Math.min(100, Math.floor(hits / 50) + 1);
}
